---
title: Voeg afgeronde hoeken toe
hero_image: images/banner.png
description: Voeg afgeronde hoeken toe aan HTML-elementen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Voeg afgeronde hoeken toe
