title: Add rounded corners
hero_image: images/banner.png
description: Add rounded corners to HTML elements.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add rounded corners
